### ISSUE TITLE
Translate to Chinese https://reactpatterns.cn/

### ISSUE THREAD

**Issue by keelii** [chantastic/sites#10]
Chinese translate version is available: https://reactpatterns.cn/

And could we add a all translation version entry to home page 🤔

**Comment by chantastic** [comment]
Hi Keelii,

I'm sorry that it took me so long to respond to this.
Only just getting deep into my inbox is the translated version no longer available at this domain?

Thank you for updating me.
I will close the issue for now but feel free to re-open.

Michael

**Comment by keelii** [comment]
@chantastic Sure, My Chinese translated version is available at https://reactpatterns.cn/

**Comment by chantastic** [comment]
added. thanks!
