### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by crocarneiro** [chantastic/sites#3]
Hi!

I'm translating this e-book to portuguese (pt-br). The work is in progress yet. My repo is [https://github.com/crocarneiro/react-patterns-traducao](https://github.com/crocarneiro/react-patterns-traducao) and it's published here [http://www.carlos.carneiro.nom.br/react-patterns-traducao/](http://www.carlos.carneiro.nom.br/react-patterns-traducao/).

In README I put the link to you repo. How can I give you the credits?

Att.

**Comment by chantastic** [comment]
All the best!
